Inspired by https://joelgrus.com/2016/05/23/fizz-buzz-in-tensorflow/

In [1]:
import torch
import numpy as np
from torch import nn

We will represent input numbers as bits. We'll  support 12-bit numbers, in the range [0,4095]. We will train on number in [101, 4095]. The final test will be, per problem definition, in [1, 100].

In [2]:
BITS = 12

In [3]:
def to_binary(i, num_bits):
    digits = np.array([i >> d & 1 for d in range(num_bits)])
    # Reverses the array to have the bits in the usual order.
    return digits[::-1].copy()

Example: convert 4 to the binary representation:

In [4]:
to_binary(4, BITS)[::-1]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The labels will be encoded as indices of the array, i.e. 0, 1, 2, and 3. The labels mark expected answers, e.g.:

* 333 is "fizz" -> 0
* 115 is "buzz" -> 1
* 225 is "fizbuzz" -> 2, etc. 

We won't label numbers < 101 because those will be used during the test.

In [18]:
label_text = [
    'fizz', 
    'buzz', 
    'fizzbuzz',
    ''
]

In [19]:
def get_label(i):
    if   i % 15 == 0: return 2
    elif i % 5  == 0: return 1
    elif i % 3  == 0: return 0
    else:             return 3

In [25]:
get_label(333), get_label(115), get_label(225)

(0, 1, 2)

Generate the training set. It's two arrays. The first array contains integers, in the bit format, the second array has the corresponding labels, in the integer format (0, 1, 2, 3) as shown above. I.e.:
```
1. train_x: [101, 102, 103, ..., 4095]
2. train_y: [  3,   0,   3, ...,    2]
```

In [26]:
train_x = np.array([to_binary(i, BITS) for i in range(101, 2**BITS)])
train_y = np.array([get_label(i) for i in range(101, 2**BITS)])

In [27]:
train_x[:3]

array([[0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1]])

In [28]:
train_y[:3]

array([3, 0, 3])

In [31]:
print([label_text[i] for i in train_y[:3]])

['', 'fizz', '']


This network is a *classifier*, i.e. it puts every input into one of the four classses: [0, 1, 2, 3] which correspond to the string values ['fizz', 'buzz', 'fizzbuzz','']. 

For classifiers we use negative log-loss function. Training the network means minimizing the value of this function.

In [37]:
loss = nn.NLLLoss()

An accuracy function calculates how many numbers we classified correctly from our test range, [1-100].

In [33]:
def accuracy(model,  loss):
    test_x = []
    test_y = []
    for i in range(1, 100):
        expect = get_label(i)
        test_x.append(to_binary(i, BITS))
        test_y.append(expect)
    x = torch.from_numpy(np.array(test_x)).float()
    y = torch.from_numpy(np.array(test_y))
    pred_y = model(x)
    pred = torch.argmax(pred_y, dim=1)
    acc = (y == pred).sum().float() / x.shape[0]
    return acc.item()

Create the model:

In [74]:
def create_net():
    return nn.Sequential(
        nn.Linear(BITS, 50),
        nn.ReLU(),
        nn.Linear(50, len(label_text)),
        nn.LogSoftmax(dim=-1)
    )

In [75]:
model = create_net()

In [76]:
opt = torch.optim.SGD(
    model.parameters(), 
    lr=5e-3, 
    momentum=0.9, 
    nesterov=True)

**Training loop**. We use stochastic gradient descent. This mean we pick a small number of training samples, e.g. 32, and performance one iteration of training on this sample. Then we pick another 32 samples, and so on. Training on smaller samples is much faster than on the data dataset every iteration.

In [77]:
import sklearn.utils 

train_x, train_y = sklearn.utils.shuffle(train_x, train_y)

train_x_t = torch.from_numpy(train_x).float()
train_y_t = torch.from_numpy(train_y)

print_every=100
batch_size = 32
test_pred = None

for i in range(500):
    batches = int(train_x.shape[0] / batch_size + 1)
    printed = False
    for b in range(batches):
        start = b * batch_size
        end = (b + 1) * batch_size
        bt = train_x_t[start:end]
        by = train_y_t[start:end]
        y_pred = model(bt)
        loss_val = loss(y_pred, by)
        model.zero_grad()
        loss_val.backward()
        opt.step()
        if i % print_every == 1 and not printed:
            print(i, b, "Loss:", loss_val.item(), "test accuracy:", accuracy(model, loss))
            printed = True
print(i, b, "Loss:", loss_val.item(), "test accuracy:", accuracy(model, loss))

1 0 Loss: 1.0706539154052734 test accuracy: 0.5353535413742065
101 0 Loss: 0.737541913986206 test accuracy: 0.6464646458625793
201 0 Loss: 0.14468005299568176 test accuracy: 1.0
301 0 Loss: 0.07151934504508972 test accuracy: 0.9898989796638489
401 0 Loss: 0.0478881299495697 test accuracy: 0.9898989796638489
499 124 Loss: 0.15687410533428192 test accuracy: 1.0


The neural network achieves 100% accuracy on the test set, i.e. in the range 1-100. 

Predict function:

1. Convert the number into the bit format.
1. Apply the train neural network to obtain the predicted 'class', i.e. 0, 1, 2, or 3.
1. Look up the text label for the returned class and print it along with original number.

In [80]:
def predict(num):
    enc = to_binary(num, BITS)
    enc = torch.from_numpy(enc).float()
    pred = model(enc)
    pred = torch.exp(pred)
    index = torch.argmax(pred).item()
    return (num, label_text[index])

In [81]:
predict(75), predict(10), predict(3), predict(21), predict(7)

((75, 'fizzbuzz'), (10, 'buzz'), (3, 'fizz'), (21, 'fizz'), (7, ''))